### ISSUE TITLE
TemperatureHumiditySensorOutdoor' object has no attribute 'setPointTemperature'

### ISSUE THREAD

**Issue by zeph** [auhlig/homematicip-exporter#4]
```casa       | 2020-11-08 11:32:04 waiting 30s before next collection cycle
casa       | Traceback (most recent call last):
casa       |   File "//./exporter.py", line 265, in collect
casa       |     self.__collect_thermostat_metrics(g.label, d)
casa       |   File "//./exporter.py", line 170, in __collect_thermostat_metrics
casa       |     if device.setPointTemperature:
casa       | AttributeError: 'TemperatureHumiditySensorOutdoor' object has no attribute 'setPointTemperature'
casa       | 
casa       | During handling of the above exception, another exception occurred:
casa       | 
casa       | Traceback (most recent call last):
casa       |   File "//./exporter.py", line 313, in <module>
casa       |     e.collect()
casa       |   File "//./exporter.py", line 275, in collect
casa       |     "collecting status from device(s) failed with: {1}".format(str(e))
casa       | IndexError: Replacement index 1 out of range for positional args tuple
casa exited with code 1
```
I will try to provide a patch

**Comment by auhlig** [comment]
Urks. That would be highly appreciated @zeph!

**Comment by janschwirtz** [comment]
It's the same problem with "TemperatureHumiditySensorWithoutDisplay".
